### ISSUE TITLE
Host file distribution

### ISSUE THREAD

**Issue by t-knapp** [gsliepen/tinc#122]
Hi Guus,

I use tinc 1.1 and played around with invite / join. I found out, that invited nodes only can connect via a relay to other (prior existing) nodes. A part (Ed25519PublicKey) of the host files are exchanged with invited nodes. 
I figured out that no direct connection is possible with hosts, their hostfile only contains the Ed25519PublicKey value and not the RSA PUBLIC KEY.

If I exchange the complete hostfiles between the nodes, direct connections are possible.

So I came up with a question: Why are only Ed25519PublicKey Values exchanged at first connection between Nodes, which do not have their complete hostfiles?

The motivation of the question is that I plan to create a cross-plattform gui with automatic host file distribution.

Kind regards
tknapp

**Comment by gsliepen** [comment]
On Mon, Sep 19, 2016 at 08:02:15AM -0700, Tobias Knapp wrote:

> I use tinc 1.1 and played around with invite / join. I found out, that invited nodes only can connect via a relay to other (prior existing) nodes. A part (Ed25519PublicKey) of the host files are exchanged with invited nodes. 
> I figured out that no direct connection is possible with hosts, their hostfile only contains the Ed25519PublicKey value and not the RSA PUBLIC KEY.

The RSA public key is only used for legacy nodes, that don't support
invitations anyway. I could add an RSA key exchange as well, but it only
makes sense if you have a VPN which also has nodes running tinc 1.0.x.

> If I exchange the complete hostfiles between the nodes, direct connections are possible.
> 
> So I came up with a question: Why are only Ed25519PublicKey Values exchanged at first connection between Nodes, which do not have their complete hostfiles?
> 
> The motivation of the question is that I plan to create a cross-plattform gui with automatic host file distribution.

Actually, the issue is probably that it only exchanges public keys
between the inviting node and the invited node. So right after the
exchange, the new node can only make a metaconnection with the inviting
node. However, that shouldn't prevent making direct UDP connections with
other nodes. Once you have such a direct connection, it will have
exchanged Ed25519 public keys with the peer of that connection, and
after that it should be able to make metaconnections. If this is not
working, then that's a bug.

You can have the inviter send all its host config files to the invitee,
by creating an invitation-created script, as described here:

https://tinc-vpn.org/documentation-1.1/Writing-an-invitation_002dcreated-script.html#Writing-an-invitation_002dcreated-script

You have to replace "tinc export" with "tinc export-all".

You can also create an invitation-accepted script that gets executed
whenever a node joined using an invitation.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by t-knapp** [comment]
> The RSA public key is only used for legacy nodes, that don't support invitations anyway. I could add an RSA key exchange as well, but it only makes sense if you have a VPN which also has nodes running tinc 1.0.x.

Thank you for bringing light into darkness.

> Actually, the issue is probably that it only exchanges public keys between the inviting node and the invited node. So right after the exchange, the new node can only make a metaconnection with the inviting node. However, that shouldn't prevent making direct UDP connections with other nodes. Once you have such a direct connection, it will have exchanged Ed25519 public keys with the peer of that connection, and after that it should be able to make metaconnections. If this is not working, then that's a bug.

I double-checked my setting again and you are totally right. As long as two nodes have one node in common (kind of 'server' node with DHCP), the host files are exchanged. And direct connections are possible after the nodes has learned each others Public Key. 

Thank you.
