### ISSUE TITLE
Tinc does not start networks in nets.core

### ISSUE THREAD

**Issue by ghost** [gsliepen/tinc#143]
Hello,
I really don't have much to add in detail to this issue as of current, but I'll try to go through and get as much detail as possible of the issue and the environment that I work on.

Upon recent installation of my Ubuntu 17.04 Server, it appears that the `tinc` service under systemd does start as expected, but however the nets.core simply appears to not be acknowledged.
I have a network named "backend" and have made sure that it is in the file, the permissions are proper on the directory, and it's contents including the shell scripts, and have confirmed that the configuration has previously worked on a Debian 8 installation running systemd.  This leads me to believe that the issue may be related to this version of ubuntu specifically.

I can however, manually run the command `tincd -n backend` to get the interface, and the tunnel working which is good.

as previously mentioned, I don't have much to add other than the symptoms, and what I have done, but will be sure to provide as much information as I can if requested.

Thanks,
Andrew

**Comment by gsliepen** [comment]
Hello Andrew,

If you have a problem with a specific distribution's package for tinc, it's best to report the bug to that distribution. For Debian derivatives, older packages used `nets.boot`, not `nets.core`. Newer packages that integrate with systemd come with a tinc service that does not do much on its own. It does not read `nets.boot`. However, instead of putting a netname in `nets.boot`, you do this:

    systemctl enable tinc@<netname>

The tinc service without the @... can be used to start and stop all netnames that have been enabled with the above command. I hope that helps.

**Comment by fangfufu** [comment]
The question has been answered 4 years ago, so I am closing the ticket.
