### ISSUE TITLE
How to share local network over tinc ?

### ISSUE THREAD

**Issue by wenerme** [gsliepen/tinc#176]
Hi, I'm new to tinc, I want to share my local network over tinc.

A: 192.168.100.1/32 master node
B: 192.168.1.0/24 client node, ip 192.168.1.105, I want to share over tinc

I follow this https://www.tinc-vpn.org/documentation/Example-configuration.html but it's not works.

I can ping B from A, but I can not ping other host in B's network, like 192.168.8.120

the setup is 

A:
ip link set $INTERFACE up
ip addr add 192.168.100.1/16 dev $INTERFACE

Subnet=192.168.100.1/32

B:
ip link set $INTERFACE up
ip addr add 192.168.1.105/16 dev $INTERFACE

Subnet = 192.168.1.0/24

I already spend days on this, please help me, thanks!

BTW, I also create a question https://unix.stackexchange.com/q/422991/47774

Sorry for post question here, I tried to join mailing list, but nothing happens, maybe need to approve.

**Comment by stevesbrain** [comment]
Host A and host B will need to have their ip address in the same range (i.e. both tinc network addresses should be in 192.168.100.0/24 - if you pop it in /16, then it will take over the addresses you're trying to route to, and you won't be able to route to them). So let's say 192.168.100.1/24 and 192.168.100.2/24. 

Then, on host B, you'll want to enable ipv4 forwarding so that it will accept incoming packets for the 192.168.1.0/24 network. On all other machines, you'll want to add routes to 192.168.1.0/24 via 192.168.100.2 (host B). They intrinsically know how to reach 192.168.100.2 as it's on their subnet, then, when they send the packet to B, B knows how to reach 192.168.1.0/24 as it's on the other network card, so it'll forward that onto the host for you.

**Comment by wenerme** [comment]
To share local network , you must run tinc on router. Also need to add tinc interface to bridge interface.

**Comment by liq05** [comment]
@wenerme 成功了吗？如何把tinc的接口进行桥接？

**Comment by wenerme** [comment]
@liq05 参考我的笔记 https://github.com/wenerme/wener/blob/master/tricks/ops/network/private/tinc.md#route 后面有时间我会写一些博客

**Comment by damnboy** [comment]
把转发打开，再把出口网卡设置成nat模式，把在hosts目录下的配置文件里吧本地网络ip加上，最后在目标机器上添加路由即可。

**Comment by balck-paint** [comment]
> 把转发打开，再把出口网卡设置成nat模式，把在hosts目录下的配置文件里吧本地网络ip加上，最后在目标机器上添加路由即可。

windows路由如何设置？我windows机器项访问linux客户端下的子网设备。linux nat转换、ip转发都设置了，windows添加要访问的子网走vpn接口，但是添加了路由实际上还是走的wlan，route add 192.168.2.0 mask 255.255.255.0 10.0.0.100 ，按说openvpn这样都没毛病呀，为什么这个就不行
