### ISSUE TITLE
tinc service not started error on stderr

### ISSUE THREAD

**Issue by Gjergj** [gsliepen/tinc#180]
Here is my situation on a windows machine:
I run tinc and it is using my last available tap adapter.
Than try to start openvpn but it gives me an error "All Tap-Windows adapters on this system are currently in use"
But when openvpn is running ok and I try to start the tinc service I get no error on stderr.
Using tinc cli I issue the start command and the output is this:

> Could not create tinc service: (1073) The specified service already exists.
tinc service started

But in reality the service has stopped because openvpn has used my only tap adapter.

Is it possible to get on stderr the reason why tincd service has not started?

**Comment by dechamps** [comment]
I would be best if you used the [mailing list](https://www.tinc-vpn.org/cgi-bin/mailman/listinfo/tinc) for such questions.

> Here is my situation on a windows machine:
> I run tinc and it is using my last available tap adapter.

If you want to select a specific adapter you can do so by using the `Interface=` configuration option. Just specify the full name of the network adapter, as it appears in the "Control Panel\Network and Internet\Network Connections" Windows UI.

(Alternatively, you can do this by interface GUID using the `Device=` configuration option.)

Likewise, OpenVPN also has options for selecting a specific adapter. This way, you can make sure tinc and OpenVPN won't conflict with each other.

> Is it possible to get on stderr the reason why tincd service has not started?

When running as a Windows service, tinc logs are sent as Windows Events that can be seen using the Windows Event Viewer.

However, when troubleshooting it is usually more convenient to run tincd directly in the console using the `-D` option. You can also pass `-d5` for full debug information.

**Comment by Gjergj** [comment]
I am writing a gui app for tinc.
My issue is not how to specify interface to tinc but if it is possible that tinc outputs such errors also on stderr.
So I am requesting this feature that would make my life easier to get the errors.
I know about debug options but that would require extra steps for the user.

**Comment by dechamps** [comment]
If you run tinc as a service, there is no stderr to begin with. You might want to use the `--logfile` option and then read errors off the logfile (perhaps even show the entire log to the user, that would be very useful). Though in that case you have the additional responsibility of rotating the logfile so that it doesn't grow infinitely.

**Comment by gsliepen** [comment]
On Thu, Feb 22, 2018 at 09:38:01AM +0000, Gjergji Ramku wrote:

> Here is my situation on a windows machine:
> I run tinc and it is using my last available tap adapter.
> Than try to start openvpn but it gives me an error "All Tap-Windows adapters on this system are currently in use"
> But when openvpn is running ok and I try to start the tinc service I get no error on stderr.
> Using tinc cli I issue the start command and the output is this:
> 
> > Could not create tinc service: (1073) The specified service already exists.
> tinc service started
> 
> But in reality the service has stopped because openvpn has used my only tap adapter.
> 
> Is it possible to get on stderr the reason why tincd service has not started?

Not unless you use the -D option. The reason is that on Windows, without
-D, it tries to run as a service. This involves installing itself as a
service, and then telling Windows to please start that service. However,
the service is a completely separate process, and there is no way for
the CLI to get any early output from it.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by Gjergj** [comment]
Ok, I figured something out to show the user some info.
