### ISSUE TITLE
Healthcheck for Tinc

### ISSUE THREAD

**Issue by jakubgs** [gsliepen/tinc#202]
I can check if the Tinc TCP port is up by doing the TCP handsheak, though that generates errors like this:
```
Metadata socket read error for <unknown> (127.0.0.1 port 59916): Connection reset by peer
```
All over the logs. And it also didn't actually check if the client is functioning.

Does Tinc have a healthcheck I can perform or TCP or UDP ports to verify it's up?

**Comment by gsliepen** [comment]
On Mon, Sep 03, 2018 at 04:32:08PM +0000, Jakub wrote:

> I can check if the Tinc TCP port is up by doing the TCP handsheak, though that generates errors like this:
> ```
> Metadata socket read error for <unknown> (127.0.0.1 port 59916): Connection reset by peer
> ```
> All over the logs. And it also didn't actually check if the client is functioning.
> 
> Does Tinc have a healthcheck I can perform or TCP or UDP ports to verify it's up?

Tinc will send a message when something connects to its TCP port, that
should start with "0 <name> 17", where <name> is the Name of the node
you connect to. But of course, if you actually want to verify it is up,
you have to connect another node to it, and then see if you can
establish a connection over the VPN.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by jakubgs** [comment]
I see, so there is no build-in healthcheck?
What exactly does the `0 <name> 17` command do?

**Comment by gsliepen** [comment]
It's message type 0, which means it is the ID message, the name is the Name of the node that sends this message, and 17 is the version of the protocol that it is using.

Note that since the latest releases, the side that initiates the TCP connection should send a valid ID message before the other side will reply. Also, if you send anything invalid, the other side will not close the connection automatically. However, another way to check the health of a node is to set up a "healthcheck" node that has a ConnectTo to one or more nodes that you want to check, and then you can use host-up/host-down scripts to have the healthcheck node respond to other nodes going online or offline. See https://tinc-vpn.org/documentation/Scripts.html.

**Comment by fangfufu** [comment]
The question has been resolved, so I am closing the ticket. @jakubgs , if you want a build-in healthcheck as a feature, please leave a comment below. I will reopen the ticket and put it down as a wishlist item.

**Comment by jakubgs** [comment]
I don't really see the point of Tinc anymore now that WireGuard is part of the kernel. I switched all of my infra to it.
The performance is just ridiculous in comparison. I recommend anyone to switch away from Tinc to WireGuard.

**Comment by fangfufu** [comment]
Well a lot of people find the peer-to-peer nature of WireGuard very useful, for example, me. I basically have two tinc nodes with public IP addresses that all my other tinc nodes connect to. My VPN network still works, if one of the public tinc node goes down. I cannot imagine how I would go about configuring WireGuard to do that.
