### ISSUE TITLE
1.1pre17 EVP_EncryptUpdate:invalid operation

### ISSUE THREAD

**Issue by ptorrent** [gsliepen/tinc#223]
Hello,

After upgrading tinc to 1.1pre17. I'm not able to join any node :

![image](https://user-images.githubusercontent.com/6083644/58459934-d692cd80-812c-11e9-8ef7-9aa7d5edb4d7.png)

I tried to downgrade libssl1.1 but without success

Thanks for your support

**Comment by furkanmustafa** [comment]
It's been fixed in `1.1` branch. But has not been released yet.

https://github.com/gsliepen/tinc/commit/2b0aeec02d64bb4724da9ff1dbc19b7d35d7c904

@gsliepen Could you consider tagging a version for this commit? 1.1pre18 ?

(For our own installations, we had to do it ourselves in our company repository)

**Comment by fangfufu** [comment]
As this seems to have been fixed 2 years ago. I am closing the ticket. Please do reopen the ticket if it still affects you.
