### ISSUE TITLE
Error looking up IP port 655: Name or service not known

### ISSUE THREAD

**Issue by tholu** [gsliepen/tinc#232]
Using tinc version 1.0.35 on Debian Buster, I get this error message frequently:

```
Error looking up IP port 655: Name or service not known
```

However, everything seems to be working OK. In my `/etc/tinc/network/hosts/nodeX` files, I specified the Address like this:

```
Address = my.public.ip.address
Subnet = 10.0.0.X
```

Should I just ignore it or how can I fix this?

**Comment by gsliepen** [comment]
Is the address a numerical IP address? If so, check if there are no accidental mistakes, such as using a comma instead of a period to separate numbers, or an extra space. Otherwise, the operating system might think it's a host*name* and try to look it up, which would then fail. In doubt, remove the Address line and type it in again.
If it is not a numeric IP address but a hostname, then check that the name is correct.

**Comment by tholu** [comment]
@gsliepen Thanks for your fast reply! And sorry, I'm dumb - it was indeed a copy+paste error, so only "IP" was specified for some hosts instead of the real public IP address.
