### ISSUE TITLE
Troubleshooting core dump on FreeBSD on a very buggy Comcast Connection

### ISSUE THREAD

**Issue by darkpixel** [gsliepen/tinc#261]
I'm running tinc-devel-1.1pre17_6 on 27 FreeBSD routers to create a mesh.

Everything ran well in testing, and continued running well in production for about 8 months.  Then last September (2020) Comcast happened. ;)

We have one site that has an absolutely terrible Comcast connection.  3-4 outages per day combined with multiple periods of high packet loss.  Comcast has been out no less than 10 times to fix the issue, but every time they show up they say "I found the problem and fixed it"...followed up by outages again a few hours later.

Anyways...Tinc apparently isn't handling this well.

On the bad Comcast connection, tinc frequently core dumps: ```pid 42745 (tincd), jid 0, uid 0: exited on signal 11 (core dumped)```.  This is preceded with multiple messages about closing connections and timeouts.

If I SSH into the router and restart the tinc daemon, it immediately reconnects to the mesh, followed ~30-60 seconds later by my monitoring system going berserk because half the routers (randomly) just had tinc core dump.

Since everything is managed by salt, the easiest way to work around this when I notice that bad Comcast router is having issues is to just trigger all the routers to restart their tinc instances.

Is there anything I can do to help debug the issue?  It usually happens anywhere from a few to tens of times per day, so I can easily replicate it.

**Comment by fangfufu** [comment]
Probably a bug, but I cannot tell if this is specific to FreeBSD.

**Comment by darkpixel** [comment]
Is there anything on my end that I can do to help troubleshoot @fangfufu ?

**Comment by fangfufu** [comment]
I am quite new to the project myself. I am just helping out. Tagging @gsliepen , since you are quite keen. 

For now, I would think that you might want to figure out how to compile the latest version tinc, if you have not done so already. I suspect you might want to log tinc's output, so the log shows what happens when it crashes.

**Comment by deliciouslytyped** [comment]
Driveby-ish comment, you can see me fighting with some stuff in https://github.com/gsliepen/tinc/issues/252 ; if you can reliably trigger the issue (and maybe even otherwise), I would
- build tinc with debug symbols
- make an `rr` recording

The `rr` recording is probably mostly useful if you are either comfortable using `gdb`, or comfortable with uploading your log file. - but I assume you don't want to expose your packets or key material.

**Comment by fangfufu** [comment]
@darkpixel I would start generating logs, please have a look at: 
https://www.tinc-vpn.org/documentation/Solving-problems.html

If the log doesn't show anything, then I would start creating debug builds as @deliciouslytyped  suggested.

**Comment by darkpixel** [comment]
Aaagh.  Comcast came through this morning and has apparently fixed their overloaded node.  I have had a single tinc death in the last 24 hours.  I appreciate the pointers everyone, and I'm a bit disappointed I didn't get a chance to build from source (it's so rare I get to do that now-a-days).

**Comment by deliciouslytyped** [comment]
Maybe it will break again soon :)

**Comment by darkpixel** [comment]
LOL--well, it *is* Comcast.
