### ISSUE TITLE
Experimental: epoll support

### ISSUE THREAD

**Issue by splitice** [gsliepen/tinc#266]
A follow on from issue #110 

Formed from https://www.cs.cornell.edu/courses/cs5413/2014fa/projects/group_of_ej222_jj329_jsh263/ for the purposes of evaluating the real world performance differences against a current version tinc 1.1

I thought I would share this branch https://github.com/X4BNet/tinc/tree/experiment/paper2

Still a WIP and not mergable (hence no PR).

**Comment by splitice** [comment]
Current notes:
 - This removes pselect / select support (no windows)
 - This uses GNU vasprintf (no windows, no non-linux)
 - double iteration in splay tree far from optimal
 - comment removal necessary
 - committed testing script from paper
 - some debug comments committed

I'll say this again, this is intended only for evaluation at this point. Under no circumstances run this fork in production.

**Comment by splitice** [comment]
OS event support:
 - BSD: kqueue / **pselect** / select
 - Android: **epoll** / pselect / select
 - Linux: **epoll** / pselect / select
 - Windows: **IOCP** / select

Bold is the intended method in my fork.

**Comment by splitice** [comment]
Double iteration can be resolved by supplying a user pointer to the event object. You can supply up to 64bits of data that the kernel will provide back to the caller of epoll_wait.

This could be a pointer to to the `io_t` perhaps? Although I'm not yet sure how the splay tree works and the safety requirements of storing the pointer.

**Comment by splitice** [comment]
I benchmarked `experiment/paper2` against the latest `1.1` branch.

The experiment branch was consistently slightly lower resource (higher performing). Around 5-7% faster depending on the test run. Performance improvement is mostly in "system" cpu usage (8%) with a small amount of user CPU usage (3%).

Testing was carried out with approx 17 k PPS in both directions (high rate ICMP ping from hping3) between DigitalOcean SFO3 and Vultr LA. Speed of 17k PPS was chosen as it is the upper rate possible with tinc on this hardware before major VPN instability occurs.

This performance improvement would likely decrease with larger packets as encryption (approx 10 - 15% of total CPU usage on small packets in my experience) would become a larger percentage.

**Comment by splitice** [comment]
Idle usage is also lower (25%). Not too important though. Likely just because of the smaller syscalls (select vs epoll).

**Comment by splitice** [comment]
@derekchiang @jasdeep-hundal

The code attached to your paper appears to have been licenced under GPL. Could you please confirm, or if willing make a release into public domain.

**Comment by splitice** [comment]
Supporting data for epoll

![](https://drive.google.com/uc?id=1YphUXfHOiSr822LiuyIZt6SBgydMXSPT)

epoll syscall CPU usage: <10%
select syscall CPU usage: >14%

Aint that just great!

**Comment by jasdeep-hundal** [comment]
@splitice : We only developed within tinc's existing code, so can confirm that anything we added would still be under GPL.

**Comment by splitice** [comment]
@jasdeep-hundal that was my understanding too. Thank you for confirmation though.

**Comment by lancethepants** [comment]
Just wanted to mention if epoll makes is into tinc. 

I run tinc on some devices (routers w/ tomato firmware) with a kernel older than 2.6.27, and thus don't support `epoll_create1`, just `epoll_create`. 

Looks like in the source code the only two instances are `epoll_create1(0)`,so epoll_create1 will have the same behavior as epoll_create,  
Maybe tinc at compile time could detect if epoll_create1 is supported and fallback to epoll_create. or else use epoll_create since that is what is happening anyway. Otherwise I will get compile time error like `undefined reference to 'epoll_create1'`.

I'm excited to see what improvements epoll could bring to tinc, particularly on low-powered devices.

**Comment by splitice** [comment]
@lancethepants I guess old create makes sense. Not like it hurts much. But damn you need a newer kernel mate.

**Comment by splitice** [comment]
@lancethepants https://github.com/X4BNet/tinc/commit/e556aaf86903ba86c0d726e96aea7501c2b9d472

done.

**Comment by splitice** [comment]
I'm reasonably happy with this. I'll clean it up into a single feature commit and branch for PR once/if my previous PRs merge.

**Comment by gsliepen** [comment]
I don't think the select loop is a performance bottleneck in tinc, we're only dealing with a handful of filedescriptors. I think reducing the number of times we have to poll (mmapped tun/tap device?) would have a bigger impact, and even better than epoll might be to use io_uring. However, if there's a clean pull request we can merge it.

**Comment by splitice** [comment]
@gslipen really? 14.85% of the CPU utilisation (for high pps / low size) is a great target in my book.

And unlike reducing a "mmaped tun" device (and io_uring) it's available for most of the Linux audience. That doesn't discount also adding support for either.

Pr will come after my current batch.

**Comment by splitice** [comment]
One other way to reduce the epoll_wait and select syscalls would be to get into non-blocking mode on the fd and read until EAGAIN. The problem with that is primarily how the current architecture is designed with an `io_t` being either in read mode or write mode with a single handler. I'm not really keen on changing that.

Given that vnet should outperform that I havent really looked into it.

My view on Linux is that there will be:
 - legacy kernel users on select (those without epoll)
 - moderately old kernel users (and those using tap) on epoll  + read + 4% (more if someone implements non-blocking reads/writes and/or integrates with the epoll user pointer to remove the double iteration)
 - modern kernel with tun using epoll + vnet (+ unknown % but I'm hoping it's at-least +50% to be worth all the effort)

That's what I'm working towards.

**Comment by gsliepen** [comment]
I agree that it's a good target to look at to improve, but use of epoll doesn't give a 14.85% CPU utilization reduction, I only see a 0.94% overall reduction in `do_syscall_64` overhead. Or am I reading it wrong?

The reason for draining writes first was that otherwise, we could read more than we could write out to a socket in response, and since we don't want to block, the only option if the send buffer was full was to terminate the connection. But this is only an issue for the meta-connections, it should be possible to handle both read and writes simultaneously for the UDP sockets. Perhaps some flag can be added to `io_t` so it can do the right thing for each socket type.

Since epoll was introduced in Linux 2.5.44, I don't think we have to worry about legacy kernel users, but then again since we have to support `select()` for other operating systems anyway, we can keep compatibility. It will be really interesting to see what performance gains we get from vnet!

**Comment by splitice** [comment]
@gsliepen 4% gain not 14%. I'm not sure if thats a typo or a mistake. Select is 14% of the total CPU consumption, with epoll in it's place it's 10%. That's a rough 4% gain.

Tail call optimization with epoll run means you need to be aware of the grouping of unrelated functions in the group. gcc was able to optimize the epoll layout of functions a bit more (resulting in a worse perf output).

**Comment by splitice** [comment]
This merged so can be closed :)
