### ISSUE TITLE
Enable Optimizations by default

### ISSUE THREAD

**Issue by splitice** [gsliepen/tinc#271]
While investigating low hanging fruit I discovered `-O3` wasnt being applied. Seems like a simple optmization to apply for non-debug builds for a small performance gain.

**Comment by fangfufu** [comment]
``-O3`` doesn't necessarily make thing faster, e.g.
https://jira.mariadb.org/browse/MDEV-19734

**Comment by fangfufu** [comment]
By the way, @splitice , have you got some benchmark related to this?

**Comment by splitice** [comment]
@fangfufu that's the exception not the norm. In my benchmarks it performs about the same (within 1%). It's not going to maker a difference for the main user of cpu time (syscalls).

**Comment by fangfufu** [comment]
@gsliepen , what do you think of this?

**Comment by gsliepen** [comment]
By default `./configure` will use `-O2`, which is the reasonable and safe choice. I would like to keep it as it is.

**Comment by gsliepen** [comment]
To clarify a bit, while code compiled with `-O2` is extremely likely to be faster than with lesser optimization levels, it's not guaranteed that `-O3` is faster, and can even be slower. Also, some people might want to optimize for size instead of speed. It's going to depend on the compiler version and architecture as well how the optimization flags will affect performance. So since `-O3` isn't a clear win, let's just keep the defaults.
